
name: Matrix-Test

on:
  workflow_dispatch:

jobs:
  matrix-test:
    strategy:
      matrix:
        fail-fast: false
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Python Test
      run: python test.py

